### ISSUE TITLE
Implement JWT Authentication btw middlelayer and the Basic API

### ISSUE THREAD

**Issue by lauraGgit** [18F/fs-middlelayer-api#36]
As an middlelayer api user, when I submit a get or post request, it properly sends information to the corresponding authenticated routes in the NRM SUDS BASIC API.

Tasks
Before any request made to basic - POST request a token from the `/login` endpoint in the API, using a Basic HTTP authorization using credentials stored in a user provider service. 
https://github.com/18F/fs-middlelayer-api/blob/master/src/controllers/index.js#L313
https://github.com/18F/fs-middlelayer-api/blob/master/src/controllers/index.js#L225

using credentials stored in a cf user-provided-service called
`nrm-suds-url-service`{SUDS_API_URL, username, password}`

Pass the token in the response to subsequent postToBasic and getFromBasic requests as a `Authorization` header
{"token": “string”}

Add the following headers key the following object to the options objects of the following requests:
headers: {
‘Authorization’: `Bearer ${token}`,
}
https://github.com/18F/fs-middlelayer-api/blob/master/src/controllers/basic.js#L221
https://github.com/18F/fs-middlelayer-api/blob/master/src/controllers/basic.js#L221
https://github.com/18F/fs-middlelayer-api/blob/master/src/controllers/basic.js#L221
https://github.com/18F/fs-middlelayer-api/blob/master/src/controllers/basic.js#L221

Update corresponding tests

**Comment by mgwalker** [comment]
Going to write down here what I understand from a more detailed conversation with @lauraGgit 

1. A request comes from web into middle layer API; the middle layer API needs to hit the SUDS basic API in order to fulfill the request
2. The middle layer sends authentication request to SUDS API at `/login`, using HTTP basic authentication with credentials from env, to get a SUDS token
3. The SUDS API returns `{ "token": "jwt-token-string" }` - this is the SUDS token
4. The middle layer API sends `POST` or `GET` (as needed according to step 1) to SUDS API and includes an Authorization header as a bearer token (`Authorization: bearer {SUDS token}`)

**Comment by lauraGgit** [comment]
@mgwalker that looks right!

**Comment by lauraGgit** [comment]
Fixed by #48
